# Generated by Django 5.2.1 on 2025-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_jenis_barang_tgl_input_barang_id_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='link_gbr',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
